### ISSUE TITLE
error: package com.reactlibrary does not exist import com.reactlibrary.RNVideoHelperPackage;                        ^

### ISSUE THREAD

**Issue by mavrickdeveloper** [shuftipro/React-Native-SDK#1]
Hello guys 
Code is having issues compiling : "yarn android"

```
error : error: package com.reactlibrary does not exist
import com.reactlibrary.RNVideoHelperPackage;
                       ^
```

**Comment by shuftipro** [comment]
> Hello guys
> Code is having issues compiling : "yarn android"
> 
> ```
> error : error: package com.reactlibrary does not exist
> import com.reactlibrary.RNVideoHelperPackage;
>                        ^
> ```

It seems that you are missing the video helper package for the react native SDK. You may import this package to continue.
https://www.npmjs.com/package/react-native-video-helper
