### ISSUE TITLE
Supporting Different Languages

### ISSUE THREAD

**Issue by httpstersk** [shuftipro/React-Native-SDK#2]
Hey 👋

The `language` property which is passed to the config object (`verificationObj`) is ignored and not used at all in the codebase. The UI components have hard-coded descriptions in English.

For example:
```
<Text style={styles.pTextBold}>Ready to take Photo?</Text>
<Text style={styles.pText}>Take the frontside photo of your</Text>
<Text style={styles.pText}> Pakistani Passport </Text>
```

**Comment by shuftipro** [comment]
> Hey 👋
> 
> The `language` property which is passed to the config object (`verificationObj`) is ignored and not used at all in the codebase. The UI components have hard-coded descriptions in English.
> 
> For example:
> 
> ```
> <Text style={styles.pTextBold}>Ready to take Photo?</Text>
> <Text style={styles.pText}>Take the frontside photo of your</Text>
> <Text style={styles.pText}> Pakistani Passport </Text>
> ```

As of now, the native SDK does not support multiple languages. This is currently on our time-line for development and we'll keep you updated about its status.
