### ISSUE TITLE
Could not resolve dependency

### ISSUE THREAD

**Issue by mrmzufry** [shuftipro/React-Native-SDK#3]
Installation through npm in react native, gives the following error. Can you help?

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: first_react_app@0.0.1
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.14.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-native@0.68.2
npm ERR! node_modules/react-native
npm ERR!   peer react-native@"^0.0.0-0 || 0.60 - 0.68 || 1000.0.0" from @react-native-async-storage/async-storage@1.17.5
npm ERR!   node_modules/@react-native-async-storage/async-storage
npm ERR!     peer @react-native-async-storage/async-storage@"^1.13.4" from react-native-shuftipro-kyc@1.1.8
npm ERR!     node_modules/react-native-shuftipro-kyc
npm ERR!       react-native-shuftipro-kyc@"*" from the root project
npm ERR!       1 more (react-native-shuftipro-kyc)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by shuftipro** [comment]
Hello there @mrmzufry,

I wanted to inform you that we've just rolled out an update to our react-native SDK. Could you please give it another shot? If you continue to encounter any problems, we would greatly appreciate it if you could provide us with your feedback.

Thank you very much.
